theme = "flamingo_galaxy"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[keys.normal.space]
x = [
  ":write-all",
  ":insert-output scooter --hidden >/dev/tty",
  ":redraw",
  ":reload-all"
]
e = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-h21a434",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":redraw",
  ":set mouse false",
  ":set mouse true"
]
