theme = "base16_transparent"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[keys.normal.space]
x = [
  ":write-all",
  ":insert-output scooter --hidden >/dev/tty",
  ":redraw",
  ":reload-all"
]
e = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ":set mouse false",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-h21a434",
  ":redraw",
  ":set mouse true",
  ":open /tmp/unique-file-h21a434",
  "select_all",
  "split_selection_on_newline",
  "goto_file",
  ":buffer-close! /tmp/files2open"
]
